### ISSUE TITLE
【改进】细分更多种类的漏斗

### ISSUE THREAD

**Issue by Noogear** [ranminecraft/ChunkHopper#1]
谢谢大佬，插件很好用。我有个小小的意见能否参考一下呢？就是漏斗可以根据名称决定他收集的内容，比如说我可以把它分成作物漏斗、矿物漏斗等。现在的实现方式是检测名称再检测物品列表，而根据名称检测可以把配置文件修改成

> hopper:
>   name: [item, item, item]
>   nema2: [item, item, item]

的形式，先检索hepper里是否有该名称，再获取该名称下对应的list，对于性能来说几乎没差，但是会有更好的自定义性。希望能考虑，谢谢啦

**Comment by RanMinecraft** [comment]
收到！🫡

**Comment by Noogear** [comment]
> 收到！🫡

大佬有在做嘛~~~（期待）

**Comment by RanMinecraft** [comment]
> > 收到！🫡
> 
> 大佬有在做嘛~~~（期待）

完成了

**Comment by Noogear** [comment]
> > > 收到！🫡
> > 
> > 
> > 大佬有在做嘛~~~（期待）
> 
> 完成了

好滴，我晚上测试一下，测试完马上给您反馈
