### ISSUE TITLE
【BUG】地狱和末地放不了漏斗

### ISSUE THREAD

**Issue by Noogear** [ranminecraft/ChunkHopper#4]
![QQ_1726078652595](https://github.com/user-attachments/assets/bdc1bcba-df9d-47c6-8ef6-c5fbdd63d071)
我插件加了bentobox的空岛，你那边有这个问题不
我自己测试了一下，他在末地和地狱放漏斗，会去计算主世界的对应区块，主世界的对应区块又是不加载的，所以就会一直计算，应该是在String chunkName = block.getChunk().toString()这一步有问题

**Comment by RanMinecraft** [comment]
什么版本什么核心呢 插件是最新版本吗

**Comment by Noogear** [comment]
> 什么版本什么核心呢 插件是最新版本吗

新补充，原版世界也有这个问题，端是leaf1.21.1，插件肯定是最新的，论坛你构建的那个版本还是我换paper最新api构建的版本都有这个问题
![QQ_1726081034213](https://github.com/user-attachments/assets/37cc0f6c-8d2d-405c-8775-0e0a3dd1a9e6)
我把chunkname输出到控制台的效果

**Comment by Noogear** [comment]
要不把这个计算结果保存到pdc里算了，每次就取pdc里的值，重启服务器也不用重新计算

**Comment by Noogear** [comment]
或者chunkname用world name+chunkkey组成吧？

**Comment by Noogear** [comment]
经过我的测试，我推翻了自己的结论，感觉是getChunk有问题，在地狱和末地使用getchunk会获取到主世界的区块，我已经改好了pdc的版本，但是地狱和末地依旧用不了，今天应该是没法子解决了= =、我去问问leaf相关人员

**Comment by Noogear** [comment]
PaperLib.getChunkAtAsync(block.getLocation()).thenAccept(chunk -> countHopper(block));可能也有问题

**Comment by RanMinecraft** [comment]
已修复
